name: Test CI | Sematic Versions

on:
  push:
    branches:
      - main

jobs:
  build-img:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Generate Versions
        id: versioning
        uses: paulhatch/semantic-version@v4.0.2
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat"
          # A string to determine the format of the version output
          format: "v${major}.${minor}.${patch}-prerelease${increment}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push C++ environment ${{ steps.versioning.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            esmundosu/cpp.dev-environment:${{ steps.versioning.outputs.version }}
            esmundosu/cpp.dev-environment:latest

      - name: Create Release
        if: ${{ !startsWith(github.ref, 'ref/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          prerelease: true
